version: '3.1'

services:
  # Mongo database
  bsc_dex:
    container_name: bsc_dex_database
    image: mongo:6.0.3
    restart: always
    environment:
      # For create root user to manage the whole of mongo
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      # For create specific user and database then grant permission to user on that database
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
      DATABASE_NAME: $DATABASE_NAME
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "${DATABASE_PORT}:27017"

  # Redis
  redis:
    image: redis:7.0.8
    container_name: bsc_dex_redis
    ports:
      - "${REDIS_PORT}:6379"
